apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: es-data-db
  nfs:
    server: 10.128.15.196
    path: /data
